// =============================================================================
// tetra_rrc_filter.v — TX RRC Pulse-Shaping Filter (Polyphase Interpolator)
// =============================================================================
// ETSI EN 300 392-2 §9.5 (TETRA pulse shaping, α=0.35)
//
// Upsamples π/4-DQPSK symbols from 18 ksym/s to 72 kHz (L=4 interpolation)
// using a 33-tap RRC filter (α=0.35) in polyphase decomposition.
//
// Polyphase decomposition (L=4, N=33 taps):
//   Phase 0: h[ 0],h[ 4],h[ 8],h[12],h[16],h[20],h[24],h[28],h[32]  9 taps
//   Phase 1: h[ 1],h[ 5],h[ 9],h[13],h[17],h[21],h[25],h[29]         8 taps + 1 zero pad
//   Phase 2: h[ 2],h[ 6],h[10],h[14],h[18],h[22],h[26],h[30]         8 taps + 1 zero pad
//   Phase 3: h[ 3],h[ 7],h[11],h[15],h[19],h[23],h[27],h[31]         8 taps + 1 zero pad
//
//   For each input symbol, 4 output samples are produced sequentially
//   (phase 0 first). Total MAC cycles per symbol: 4×9 = 36.
//   36 cycles << 5556-cycle symbol period (100 MHz / 18 kHz).
//
// Coefficients: Q14 signed, α=0.35, 33 taps, 4 samples/symbol.
//   Identical to tetra_rx_frontend.v RRC matched filter.
//   Generated by tb/vectors/gen_rx_frontend_vectors.py
//
// Symbol shift register: 9 symbols × 16 bits = 144-bit flat bus (R3: no arrays).
//   SR[15:0] = newest symbol; SR[143:128] = oldest (tap 8).
//   Updated on each sample_valid_in pulse.
//
// MAC accumulator: 38-bit signed.
//   Cleared at tap 0 of each phase; captures acc_next (combinatorial sum of
//   all 9 taps) at tap 8, ensuring every tap contributes to the output.
//
// Pipeline (clk_sys cycles, relative to sample_valid_in):
//   Cycle  0: sample_valid_in; SR shifts with new symbol; FSM enters S_MAC
//   Cycle  1: tap=0,phase=0 — MAC begins (phase 0, tap h[0])
//   Cycle  9: tap=8,phase=0 — phase 0 output captured; sample_valid_out=0
//   Cycle 10: sample_valid_out=1 (phase 0 result)
//   Cycle 18: sample_valid_out=1 (phase 1 result)
//   Cycle 27: sample_valid_out=1 (phase 2 result)
//   Cycle 36: sample_valid_out=1 (phase 3 result); FSM returns to S_IDLE
//   Group delay: (N-1)/(2×L) = 4 symbol periods.
//
// Ports:
//   clk_sys          — 100 MHz system clock
//   rst_n_sys        — active-low async reset
//   i_in             — signed 16-bit I input from π/4-DQPSK modulator
//   q_in             — signed 16-bit Q input
//   sample_valid_in  — 1-cycle strobe at ~18 kHz (one new symbol)
//   i_out            — signed 16-bit I output to TX frontend
//   q_out            — signed 16-bit Q output
//   sample_valid_out — 1-cycle strobe at ~72 kHz (4 pulses per symbol)
//
// Resource estimate (Vivado 2022.2, xc7z020):
//   LUT  : ~60    (FSM, muxes, saturation)
//   FF   : ~230   (two 144-bit SR, two 38-bit ACC, counters, outputs)
//   DSP48: 1      (MAC multiplier, inferred)
//   BRAM : 0
// =============================================================================

`default_nettype none

module tetra_rrc_filter #(
    parameter IQ_WIDTH      = 16,
    parameter RRC_ACC_SHIFT = 14   // Q14 coefficient fractional bits
)(
    input  wire                        clk_sys,
    input  wire                        rst_n_sys,
    input  wire signed [IQ_WIDTH-1:0]  i_in,
    input  wire signed [IQ_WIDTH-1:0]  q_in,
    input  wire                        sample_valid_in,
    output reg  signed [IQ_WIDTH-1:0]  i_out,
    output reg  signed [IQ_WIDTH-1:0]  q_out,
    output reg                         sample_valid_out
);

    // -------------------------------------------------------------------------
    // Internal constants
    // -------------------------------------------------------------------------
    localparam SR_DEPTH    = 9;                       // ceil(33 taps / L=4)
    localparam SR_WIDTH    = SR_DEPTH * IQ_WIDTH;     // 144 bits
    localparam COEFF_WIDTH = 16;
    // ACC: IQ_WIDTH + COEFF_WIDTH + ceil(log2(SR_DEPTH)) = 16+16+4 = 36; use 38 for margin
    localparam ACC_WIDTH   = 38;
    localparam S_IDLE      = 1'b0;
    localparam S_MAC       = 1'b1;

    // -------------------------------------------------------------------------
    // RRC Coefficients — Q14 signed, α=0.35, 33 taps, 4 samples/symbol
    // h[k] = h[32-k] (symmetric). Identical to tetra_rx_frontend.v.
    // -------------------------------------------------------------------------
    localparam signed [15:0] H00 = 16'sh0011;  // +17
    localparam signed [15:0] H01 = 16'sh006D;  // +109
    localparam signed [15:0] H02 = 16'sh004E;  // +78
    localparam signed [15:0] H03 = 16'shFFB2;  // -78
    localparam signed [15:0] H04 = 16'shFF2F;  // -209
    localparam signed [15:0] H05 = 16'shFF87;  // -121
    localparam signed [15:0] H06 = 16'sh00D2;  // +210
    localparam signed [15:0] H07 = 16'sh0217;  // +535
    localparam signed [15:0] H08 = 16'sh01D4;  // +468
    localparam signed [15:0] H09 = 16'shFF4B;  // -181
    localparam signed [15:0] H10 = 16'shFBAC;  // -1108
    localparam signed [15:0] H11 = 16'shF9F7;  // -1545
    localparam signed [15:0] H12 = 16'shFD4A;  // -694
    localparam signed [15:0] H13 = 16'sh06A0;  // +1696
    localparam signed [15:0] H14 = 16'sh1373;  // +4979
    localparam signed [15:0] H15 = 16'sh1EA4;  // +7844
    localparam signed [15:0] H16 = 16'sh2312;  // +8978
    localparam signed [15:0] H17 = 16'sh1EA4;  // +7844
    localparam signed [15:0] H18 = 16'sh1373;  // +4979
    localparam signed [15:0] H19 = 16'sh06A0;  // +1696
    localparam signed [15:0] H20 = 16'shFD4A;  // -694
    localparam signed [15:0] H21 = 16'shF9F7;  // -1545
    localparam signed [15:0] H22 = 16'shFBAC;  // -1108
    localparam signed [15:0] H23 = 16'shFF4B;  // -181
    localparam signed [15:0] H24 = 16'sh01D4;  // +468
    localparam signed [15:0] H25 = 16'sh0217;  // +535
    localparam signed [15:0] H26 = 16'sh00D2;  // +210
    localparam signed [15:0] H27 = 16'shFF87;  // -121
    localparam signed [15:0] H28 = 16'shFF2F;  // -209
    localparam signed [15:0] H29 = 16'shFFB2;  // -78
    localparam signed [15:0] H30 = 16'sh004E;  // +78
    localparam signed [15:0] H31 = 16'sh006D;  // +109
    localparam signed [15:0] H32 = 16'sh0011;  // +17

    // =========================================================================
    // R1: Symbol shift registers — flat 144-bit bus (R3 compliant, no arrays)
    // SR[15:0] = newest, SR[143:128] = oldest (tap 8)
    // Updated on every sample_valid_in pulse.
    // =========================================================================
    reg [SR_WIDTH-1:0] i_shift_sys;
    always @(posedge clk_sys or negedge rst_n_sys) begin
        if (!rst_n_sys)
            i_shift_sys <= {SR_WIDTH{1'b0}};
        else if (sample_valid_in)
            i_shift_sys <= {i_shift_sys[SR_WIDTH-IQ_WIDTH-1:0], i_in};
    end

    reg [SR_WIDTH-1:0] q_shift_sys;
    always @(posedge clk_sys or negedge rst_n_sys) begin
        if (!rst_n_sys)
            q_shift_sys <= {SR_WIDTH{1'b0}};
        else if (sample_valid_in)
            q_shift_sys <= {q_shift_sys[SR_WIDTH-IQ_WIDTH-1:0], q_in};
    end

    // =========================================================================
    // MAC FSM — R5 three-block structure
    // =========================================================================
    localparam LAST_TAP   = 4'd8;   // SR_DEPTH - 1
    localparam LAST_PHASE = 2'd3;

    // R1: State register
    reg  mac_state_sys;
    always @(posedge clk_sys or negedge rst_n_sys) begin
        if (!rst_n_sys) mac_state_sys <= S_IDLE;
        else            mac_state_sys <= mac_next_sys;
    end

    // R5: Next-state logic (combinatorial)
    reg mac_next_sys;
    always @(*) begin
        mac_next_sys = mac_state_sys;
        case (mac_state_sys)
            S_IDLE: if (sample_valid_in)
                        mac_next_sys = S_MAC;
            S_MAC:  if (phase_cnt_sys == LAST_PHASE && mac_tap_sys == LAST_TAP)
                        mac_next_sys = S_IDLE;
            default: mac_next_sys = S_IDLE;
        endcase
    end

    // R1: Tap counter (0..8) — cycles through SR_DEPTH taps per phase
    reg [3:0] mac_tap_sys;
    always @(posedge clk_sys or negedge rst_n_sys) begin
        if (!rst_n_sys)
            mac_tap_sys <= 4'd0;
        else if (mac_state_sys == S_MAC) begin
            if (mac_tap_sys == LAST_TAP)
                mac_tap_sys <= 4'd0;
            else
                mac_tap_sys <= mac_tap_sys + 1'b1;
        end else
            mac_tap_sys <= 4'd0;
    end

    // R1: Phase counter (0..3) — increments at end of each subfilter
    reg [1:0] phase_cnt_sys;
    always @(posedge clk_sys or negedge rst_n_sys) begin
        if (!rst_n_sys)
            phase_cnt_sys <= 2'd0;
        else if (mac_state_sys == S_MAC && mac_tap_sys == LAST_TAP)
            phase_cnt_sys <= phase_cnt_sys + 1'b1;  // natural wrap 3→0
        else if (mac_state_sys == S_IDLE)
            phase_cnt_sys <= 2'd0;
    end

    // =========================================================================
    // Coefficient mux — polyphase: {phase, tap} → h[phase + 4*tap]
    // R3: no arrays; R10: always @(*)
    // 6-bit case key: {phase_cnt_sys[1:0], mac_tap_sys[3:0]}
    // =========================================================================
    reg signed [COEFF_WIDTH-1:0] coeff_sys;
    always @(*) begin
        case ({phase_cnt_sys, mac_tap_sys})
            // Phase 0: h[0],h[4],h[8],h[12],h[16],h[20],h[24],h[28],h[32]
            {2'd0, 4'd0}: coeff_sys = H00;
            {2'd0, 4'd1}: coeff_sys = H04;
            {2'd0, 4'd2}: coeff_sys = H08;
            {2'd0, 4'd3}: coeff_sys = H12;
            {2'd0, 4'd4}: coeff_sys = H16;
            {2'd0, 4'd5}: coeff_sys = H20;
            {2'd0, 4'd6}: coeff_sys = H24;
            {2'd0, 4'd7}: coeff_sys = H28;
            {2'd0, 4'd8}: coeff_sys = H32;
            // Phase 1: h[1],h[5],h[9],h[13],h[17],h[21],h[25],h[29], 0
            {2'd1, 4'd0}: coeff_sys = H01;
            {2'd1, 4'd1}: coeff_sys = H05;
            {2'd1, 4'd2}: coeff_sys = H09;
            {2'd1, 4'd3}: coeff_sys = H13;
            {2'd1, 4'd4}: coeff_sys = H17;
            {2'd1, 4'd5}: coeff_sys = H21;
            {2'd1, 4'd6}: coeff_sys = H25;
            {2'd1, 4'd7}: coeff_sys = H29;
            {2'd1, 4'd8}: coeff_sys = {COEFF_WIDTH{1'b0}};   // h[33] = 0 (pad)
            // Phase 2: h[2],h[6],h[10],h[14],h[18],h[22],h[26],h[30], 0
            {2'd2, 4'd0}: coeff_sys = H02;
            {2'd2, 4'd1}: coeff_sys = H06;
            {2'd2, 4'd2}: coeff_sys = H10;
            {2'd2, 4'd3}: coeff_sys = H14;
            {2'd2, 4'd4}: coeff_sys = H18;
            {2'd2, 4'd5}: coeff_sys = H22;
            {2'd2, 4'd6}: coeff_sys = H26;
            {2'd2, 4'd7}: coeff_sys = H30;
            {2'd2, 4'd8}: coeff_sys = {COEFF_WIDTH{1'b0}};
            // Phase 3: h[3],h[7],h[11],h[15],h[19],h[23],h[27],h[31], 0
            {2'd3, 4'd0}: coeff_sys = H03;
            {2'd3, 4'd1}: coeff_sys = H07;
            {2'd3, 4'd2}: coeff_sys = H11;
            {2'd3, 4'd3}: coeff_sys = H15;
            {2'd3, 4'd4}: coeff_sys = H19;
            {2'd3, 4'd5}: coeff_sys = H23;
            {2'd3, 4'd6}: coeff_sys = H27;
            {2'd3, 4'd7}: coeff_sys = H31;
            {2'd3, 4'd8}: coeff_sys = {COEFF_WIDTH{1'b0}};
            default:      coeff_sys = {COEFF_WIDTH{1'b0}};
        endcase
    end

    // =========================================================================
    // Tap data mux — polyphase tap k = SR[k*IQ_WIDTH +: IQ_WIDTH]
    // tap 0 = newest symbol (SR[15:0]); tap 8 = oldest (SR[143:128])
    // R3: variable indexed part-select on flat bus
    // =========================================================================
    wire signed [IQ_WIDTH-1:0] i_tap_sys;
    wire signed [IQ_WIDTH-1:0] q_tap_sys;
    assign i_tap_sys = $signed(i_shift_sys[mac_tap_sys * IQ_WIDTH +: IQ_WIDTH]);
    assign q_tap_sys = $signed(q_shift_sys[mac_tap_sys * IQ_WIDTH +: IQ_WIDTH]);

    // =========================================================================
    // MAC multiply — 16×16 signed → 32-bit (synthesises to 1 DSP48E1)
    // =========================================================================
    wire signed [31:0] i_product_sys = i_tap_sys * coeff_sys;
    wire signed [31:0] q_product_sys = q_tap_sys * coeff_sys;

    // Sign-extend products to ACC_WIDTH
    wire signed [ACC_WIDTH-1:0] i_prod_ext_sys;
    wire signed [ACC_WIDTH-1:0] q_prod_ext_sys;
    assign i_prod_ext_sys = {{(ACC_WIDTH-32){i_product_sys[31]}}, i_product_sys};
    assign q_prod_ext_sys = {{(ACC_WIDTH-32){q_product_sys[31]}}, q_product_sys};

    // =========================================================================
    // R1: MAC accumulators — cleared at tap 0 of each phase
    // =========================================================================
    reg signed [ACC_WIDTH-1:0] i_acc_sys;
    always @(posedge clk_sys or negedge rst_n_sys) begin
        if (!rst_n_sys)
            i_acc_sys <= {ACC_WIDTH{1'b0}};
        else if (mac_state_sys == S_MAC) begin
            if (mac_tap_sys == 4'd0)
                i_acc_sys <= i_prod_ext_sys;         // clear + load tap 0
            else
                i_acc_sys <= i_acc_sys + i_prod_ext_sys;
        end
    end

    reg signed [ACC_WIDTH-1:0] q_acc_sys;
    always @(posedge clk_sys or negedge rst_n_sys) begin
        if (!rst_n_sys)
            q_acc_sys <= {ACC_WIDTH{1'b0}};
        else if (mac_state_sys == S_MAC) begin
            if (mac_tap_sys == 4'd0)
                q_acc_sys <= q_prod_ext_sys;
            else
                q_acc_sys <= q_acc_sys + q_prod_ext_sys;
        end
    end

    // =========================================================================
    // Combinatorial accumulator + current product (acc_next).
    // On last tap (tap 8): acc_sys holds taps 0..7; acc_next holds taps 0..8.
    // Output captures acc_next so all 9 taps are included.
    // =========================================================================
    wire signed [ACC_WIDTH-1:0] i_acc_next_sys =
        (mac_tap_sys == 4'd0) ? i_prod_ext_sys
                              : i_acc_sys + i_prod_ext_sys;
    wire signed [ACC_WIDTH-1:0] q_acc_next_sys =
        (mac_tap_sys == 4'd0) ? q_prod_ext_sys
                              : q_acc_sys + q_prod_ext_sys;

    // =========================================================================
    // Output saturation — shift right by ACC_SHIFT (remove Q14 fraction),
    // then saturate to IQ_WIDTH.  Uses acc_next to include all taps.
    // =========================================================================
    wire signed [ACC_WIDTH-1:0] i_shifted_sys = i_acc_next_sys >>> RRC_ACC_SHIFT;
    wire signed [ACC_WIDTH-1:0] q_shifted_sys = q_acc_next_sys >>> RRC_ACC_SHIFT;

    // Overflow: top (ACC_WIDTH - IQ_WIDTH + 1) bits must all equal sign bit
    wire i_ovf_sys = (~(&i_shifted_sys[ACC_WIDTH-1:IQ_WIDTH-1])) &&
                     (| i_shifted_sys[ACC_WIDTH-1:IQ_WIDTH-1]);
    wire q_ovf_sys = (~(&q_shifted_sys[ACC_WIDTH-1:IQ_WIDTH-1])) &&
                     (| q_shifted_sys[ACC_WIDTH-1:IQ_WIDTH-1]);

    wire signed [IQ_WIDTH-1:0] i_sat_sys =
        i_ovf_sys ? (i_shifted_sys[ACC_WIDTH-1] ? {1'b1, {(IQ_WIDTH-1){1'b0}}}   // min
                                                 : {1'b0, {(IQ_WIDTH-1){1'b1}}})  // max
                  : i_shifted_sys[IQ_WIDTH-1:0];

    wire signed [IQ_WIDTH-1:0] q_sat_sys =
        q_ovf_sys ? (q_shifted_sys[ACC_WIDTH-1] ? {1'b1, {(IQ_WIDTH-1){1'b0}}}
                                                 : {1'b0, {(IQ_WIDTH-1){1'b1}}})
                  : q_shifted_sys[IQ_WIDTH-1:0];

    // Phase done: last tap of each subfilter (captures i_sat_sys / q_sat_sys)
    wire phase_done_w = (mac_state_sys == S_MAC) && (mac_tap_sys == LAST_TAP);

    // =========================================================================
    // R1: Output registers
    // =========================================================================
    always @(posedge clk_sys or negedge rst_n_sys) begin
        if (!rst_n_sys) i_out <= {IQ_WIDTH{1'b0}};
        else if (phase_done_w) i_out <= i_sat_sys;
    end

    always @(posedge clk_sys or negedge rst_n_sys) begin
        if (!rst_n_sys) q_out <= {IQ_WIDTH{1'b0}};
        else if (phase_done_w) q_out <= q_sat_sys;
    end

    // R1: sample_valid_out — 1-cycle delayed phase_done (pipeline stage)
    always @(posedge clk_sys or negedge rst_n_sys) begin
        if (!rst_n_sys) sample_valid_out <= 1'b0;
        else            sample_valid_out <= phase_done_w;
    end

endmodule
`default_nettype wire
