// =============================================================================
// tb_sch_f_encoder.v — unit test for tetra_sch_f_encoder
//
// Expected vectors generated by scripts/gen_sch_f_tv.py using the primitive
// CRC-16 / rate-1/4 / puncture helpers from verify_sb1_encoder.py. The
// Python path has been bit-exact against RTL for BSCH and SCH/HD, so we
// trust it as the reference reference for the sized-up SCH/F chain. Matches
// the SW encoder tetra_schf_encode() in sw/tetra_hal.c.
// =============================================================================
`timescale 1ns / 1ps
`default_nettype none

module tb_sch_f_encoder;
 reg clk = 1'b0;
 reg rst_n = 1'b0;
 reg encode_start = 1'b0;
 reg [267:0] info_bits = 268'd0;
 reg [31:0] scramble_init = 32'd0;
 wire [431:0] coded_bits;
 wire coded_valid;

 always #5 clk = ~clk;

 tetra_sch_f_encoder dut (
.clk (clk),
.rst_n (rst_n),
.encode_start (encode_start),
.info_bits (info_bits),
.scramble_init(scramble_init),
.coded_bits (coded_bits),
.coded_valid (coded_valid)
 );

 integer fail_count = 0;
 integer test_count = 0;

 task automatic run_vector(input [267:0] info,
 input [31:0] init,
 input [431:0] expected,
 input [127:0] tag);
 integer wait_cycles;
 begin
 test_count = test_count + 1;
 @(posedge clk);
 info_bits <= info;
 scramble_init <= init;
 encode_start <= 1'b1;
 @(posedge clk);
 encode_start <= 1'b0;
 // Let the DUT's S_IDLE→S_CRC transition clear coded_valid
 @(posedge clk);
 wait_cycles = 0;
 while (!coded_valid && wait_cycles < 2000) begin
 @(posedge clk);
 wait_cycles = wait_cycles + 1;
 end
 if (!coded_valid) begin
 $display("[T%0d %0s] TIMEOUT (cycles=%0d)", test_count, tag, wait_cycles);
 fail_count = fail_count + 1;
 end else if (coded_bits !== expected) begin
 $display("[T%0d %0s] FAIL (cycles=%0d)", test_count, tag, wait_cycles);
 $display(" got = %0108h", coded_bits);
 $display(" exp = %0108h", expected);
 $display(" xor = %0108h", coded_bits ^ expected);
 fail_count = fail_count + 1;
 end else begin
 $display("[T%0d %0s] PASS (cycles=%0d) coded=%0108h",
 test_count, tag, wait_cycles, coded_bits);
 end
 // Idle a cycle so coded_valid is re-armed before next vector
 @(posedge clk);
 end
 endtask

 initial begin
 $dumpfile("sim_out/tb_sch_f_encoder.vcd");
 $dumpvars(0, tb_sch_f_encoder);

 rst_n = 1'b0;
 repeat (4) @(posedge clk);
 rst_n = 1'b1;
 @(posedge clk);

 // ----- T1: all-zero info, scramble init=0 → LFSR stays 0 → mask=0 ---
 run_vector(268'h0,
 32'h00000000,
 432'h000048000000000800000000000000100000000010000000001000000000120000000000000000000200000000000000000000000004,
 "zeros_init0");

 // ----- T2: all-zero info, scramble init=3 (BSCH-style seed) --------
 run_vector(268'h0,
 32'h00000003,
 432'hbff4b99ac047a2a6a3a2f02fbf4ab91d9595652939325694aeb6da5faa9c8bc3305922ac737ed0ca4578ca23366e3e612715ca75d11a,
 "zeros_init3");

 // ----- T3: all-ones info, cell-specific init (our cell DL seed) ----
 run_vector({268{1'b1}},
 32'hE1670EC7,
 432'h06db617362627e3563c8aaf577d151263af86f0747974d5bec9c4642af74bd74917a9401cb10e126420dbc24cc647c22c66de86cd470,
 "ones_cell");

 // ----- T4: 0xA5 repeating (low 268 bits), cell-specific init -------
 run_vector(268'h5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5,
 32'hE1670EC7,
 432'hdac6a8af7fa3a228a214a734a2cc907a2738b31a864b51ba3083879eb2b57369508689c0170d24fa5fcc60190db861e31e7029b0c9b5,
 "a5_rep_cell");

 // ----- T5: determinism — rerun T3 and require identical output -----
 run_vector({268{1'b1}},
 32'hE1670EC7,
 432'h06db617362627e3563c8aaf577d151263af86f0747974d5bec9c4642af74bd74917a9401cb10e126420dbc24cc647c22c66de86cd470,
 "ones_cell_rpt");

 $display("=============================================");
 if (fail_count == 0)
 $display("tb_sch_f_encoder: PASS (%0d/%0d)", test_count, test_count);
 else
 $display("tb_sch_f_encoder: FAIL (%0d/%0d failures)",
 fail_count, test_count);
 $display("=============================================");
 $finish;
 end

 initial begin
 #1000000;
 $display("tb_sch_f_encoder: hard timeout");
 $finish;
 end

endmodule

`default_nettype wire
