// =============================================================================
// tb_sch_hd_encoder.v — unit test for tetra_sch_hd_encoder
//
// Expected vectors generated by scripts/gen_sch_hd_tv.py using the primitive
// CRC-16 / rate-1/4 / puncture helpers from verify_sb1_encoder.py. The
// Python path has been bit-exact against RTL for BSCH, so we trust it as the
// reference reference for the sized-up SCH/HD chain.
// =============================================================================
`timescale 1ns / 1ps
`default_nettype none

module tb_sch_hd_encoder;
 reg clk = 1'b0;
 reg rst_n = 1'b0;
 reg encode_start = 1'b0;
 reg [123:0] info_bits = 124'd0;
 reg [31:0] scramble_init = 32'd0;
 wire [215:0] coded_bits;
 wire coded_valid;

 always #5 clk = ~clk;

 tetra_sch_hd_encoder dut (
.clk (clk),
.rst_n (rst_n),
.encode_start (encode_start),
.info_bits (info_bits),
.scramble_init(scramble_init),
.coded_bits (coded_bits),
.coded_valid (coded_valid)
 );

 integer fail_count = 0;
 integer test_count = 0;

 task automatic run_vector(input [123:0] info,
 input [31:0] init,
 input [215:0] expected,
 input [127:0] tag);
 integer wait_cycles;
 begin
 test_count = test_count + 1;
 @(posedge clk);
 info_bits <= info;
 scramble_init <= init;
 encode_start <= 1'b1;
 @(posedge clk);
 encode_start <= 1'b0;
 // Let the DUT's S_IDLE→S_CRC transition clear coded_valid
 @(posedge clk);
 wait_cycles = 0;
 while (!coded_valid && wait_cycles < 1000) begin
 @(posedge clk);
 wait_cycles = wait_cycles + 1;
 end
 if (!coded_valid) begin
 $display("[T%0d %0s] TIMEOUT (cycles=%0d)", test_count, tag, wait_cycles);
 fail_count = fail_count + 1;
 end else if (coded_bits !== expected) begin
 $display("[T%0d %0s] FAIL (cycles=%0d)", test_count, tag, wait_cycles);
 $display(" got = %054h", coded_bits);
 $display(" exp = %054h", expected);
 $display(" xor = %054h", coded_bits ^ expected);
 fail_count = fail_count + 1;
 end else begin
 $display("[T%0d %0s] PASS (cycles=%0d) coded=%054h",
 test_count, tag, wait_cycles, coded_bits);
 end
 // Idle a cycle so coded_valid is re-armed before next vector
 @(posedge clk);
 end
 endtask

 initial begin
 $dumpfile("sim_out/tb_sch_hd_encoder.vcd");
 $dumpvars(0, tb_sch_hd_encoder);

 rst_n = 1'b0;
 repeat (4) @(posedge clk);
 rst_n = 1'b1;
 @(posedge clk);

 // ----- T1: all-zero info, scramble init=0 → LFSR stays 0 → mask=0 ---
 run_vector(124'h0,
 32'h00000000,
 216'h801200000100048000004800000080020008002000800240000004,
 "zeros_init0");

 // ----- T2: all-zero info, scramble init=3 (BSCH-style seed) --------
 run_vector(124'h0,
 32'h00000003,
 216'h3fe6f19ac147a62ea3a2b82fbf4a390f959d650929b254d4aea6de,
 "zeros_init3");

 // ----- T3: all-ones info, cell-specific init -----------------------
 run_vector({124{1'b1}},
 32'hE1670C03,
 216'hacbba9273c54bd5951c3acafe4e4307d57105e508de6791610f39b,
 "ones_cell");

 // ----- T4: D-LOC-UPDATE ACCEPT vector matching the PDU-builder TB --
 run_vector(124'h1200041601202246800000000000000,
 32'hE1670C03,
 216'hd23ac591f62b1b1a34717e5650bf17cbc8d4d88dea088373068cf2,
 "dlu_t1");

 // ----- T5: determinism — rerun T4 and require identical output -----
 run_vector(124'h1200041601202246800000000000000,
 32'hE1670C03,
 216'hd23ac591f62b1b1a34717e5650bf17cbc8d4d88dea088373068cf2,
 "dlu_t1_rpt");

 $display("=============================================");
 if (fail_count == 0)
 $display("tb_sch_hd_encoder: PASS (%0d/%0d)", test_count, test_count);
 else
 $display("tb_sch_hd_encoder: FAIL (%0d/%0d failures)",
 fail_count, test_count);
 $display("=============================================");
 $finish;
 end

 initial begin
 #500000;
 $display("tb_sch_hd_encoder: hard timeout");
 $finish;
 end

endmodule

`default_nettype wire
