// =============================================================================
// Testbench: tb_tetra_rx_frontend
// Project:   tetra-zynq-phy
// File:      tb/tb_tetra_rx_frontend.v
//
// Self-checking testbench for tetra_rx_frontend.v.
// Exercises the XPM async FIFO CDC, CIC decimator, and RRC matched filter.
//
// Test structure:
//   Test 0 — Reset:      All outputs zero during reset; no valid pulses.
//   Test 1 — DC:         DC input (I=0.5, Q=0) passes CIC+RRC; output stable.
//   Test 2 — 1 kHz tone: Single complex tone within TETRA channel bandwidth.
//   Test 3 — π/4-DQPSK:  Modulated symbols with TX-RRC pulse shaping.
//   Test 4 — Strobe check: Decimation ratio verified per test phase.
//
// Each test runs INDEPENDENTLY with a DUT reset between tests.
// Expected vectors were generated per-test in isolation by
// tb/vectors/gen_rx_frontend_vectors.py.
//
// Vector files (generated by tb/vectors/gen_rx_frontend_vectors.py):
//   rx_frontend_stimulus.hex   — ADC-rate IQ stimulus (32-bit: I[31:16] Q[15:0])
//   rx_frontend_expected.hex   — Expected filtered IQ output (32-bit: I[31:16] Q[15:0])
//
// Stimulus layout (matches gen script):
//   Lines   0..2943  : Test 1 DC      (2944 samples = 46 CIC outputs)
//   Lines 2944..6399  : Test 2 TONE   (3456 samples = 54 CIC outputs)
//   Lines 6400..9087  : Test 3 DQPSK  (2688 samples = 42 CIC outputs)
//
// Expected layout:
//   Lines  0..7   : Test 1 DC    first 8 outputs
//   Lines  8..23  : Test 2 TONE  first 16 outputs
//   Lines 24..33  : Test 3 DQPSK first 10 outputs
//
// Pass criterion: error_count == 0; each output within TOLERANCE LSBs of expected.
//
// Simulation setup:
//   clk_lvds: 4.608 MHz → period 217 ns (models AD9361 DATA_CLK/2 at 4.608 MHz)
//   clk_sys:  100 MHz  → period 10 ns
//   rst: asserted for 20 lvds + 40 sys cycles between tests
//
// Ref: ETSI EN 300 392-2 §9.5 (RRC, α=0.35)
//      Xilinx UG974 (xpm_fifo_async)
// =============================================================================

`timescale 1ns / 1ps

module tb_tetra_rx_frontend;

// =============================================================================
// Parameters matching DUT
// =============================================================================
localparam IQ_WIDTH  = 16;
localparam CIC_ORDER = 5;
localparam CIC_R     = 64;
localparam RRC_TAPS  = 33;

// Comparison tolerance: quantisation and rounding in Q14 arithmetic
localparam TOLERANCE = 32;

// Maximum vectors
localparam MAX_STIM   = 9088;
localparam MAX_EXP    = 34;

// Stimulus phase boundaries (matches gen_rx_frontend_vectors.py)
localparam DC_STIM_START    = 0;
localparam DC_STIM_LEN      = 2944;   // 46 CIC outputs
localparam TONE_STIM_START  = 2944;
localparam TONE_STIM_LEN    = 3456;   // 54 CIC outputs
localparam DQPSK_STIM_START = 6400;
localparam DQPSK_STIM_LEN   = 2688;   // 42 CIC outputs

// Expected vector counts per test phase
localparam DC_EXP_COUNT   = 8;
localparam TONE_EXP_COUNT = 16;
localparam DQPSK_EXP_COUNT= 10;

// =============================================================================
// Clock and reset generation
// =============================================================================
localparam LVDS_HALF_PERIOD = 109;    // ns (~4.587 MHz)
localparam SYS_HALF_PERIOD  = 5;     // ns (100 MHz)

reg clk_lvds;
reg clk_sys;
reg rst_n_lvds;
reg rst_n_sys;

initial clk_lvds = 1'b0;
always #(LVDS_HALF_PERIOD) clk_lvds = ~clk_lvds;

initial clk_sys  = 1'b0;
always #(SYS_HALF_PERIOD)  clk_sys  = ~clk_sys;

// =============================================================================
// DUT signals
// =============================================================================
reg  signed [IQ_WIDTH-1:0]  rx_i_lvds;
reg  signed [IQ_WIDTH-1:0]  rx_q_lvds;
reg                         rx_valid_lvds;

wire signed [IQ_WIDTH-1:0]  i_out_sys;
wire signed [IQ_WIDTH-1:0]  q_out_sys;
wire                        out_valid_sys;

// =============================================================================
// DUT instantiation
// =============================================================================
tetra_rx_frontend #(
    .IQ_WIDTH      (IQ_WIDTH),
    .CIC_ORDER     (CIC_ORDER),
    .CIC_R         (CIC_R),
    .CIC_M         (1),
    .RRC_TAPS      (RRC_TAPS),
    .RRC_ACC_SHIFT (14)
) dut (
    .clk_sys       (clk_sys),
    .rst_n_sys     (rst_n_sys),
    .clk_lvds      (clk_lvds),
    .rst_n_lvds    (rst_n_lvds),
    .rx_i_lvds     (rx_i_lvds),
    .rx_q_lvds     (rx_q_lvds),
    .rx_valid_lvds (rx_valid_lvds),
    .i_out_sys     (i_out_sys),
    .q_out_sys     (q_out_sys),
    .out_valid_sys (out_valid_sys),
    .loopback_en_sys(1'b0)          // TB tests RF-mode CIC gain
);

// =============================================================================
// Test vector storage
// =============================================================================
reg [31:0] stim_mem [0:MAX_STIM-1];
reg [31:0] exp_mem  [0:MAX_EXP-1];

// =============================================================================
// Bookkeeping
// =============================================================================
integer error_count;
integer valid_count;      // total valid pulses across all phases
integer phase_valid_count; // valid pulses in current test phase
integer exp_idx;          // current expected vector index (0..MAX_EXP-1)
integer exp_start;        // expected index range start for current phase
integer exp_len;          // number of expected vectors for current phase
integer stim_idx;
integer i;

// =============================================================================
// Waveform dump
// =============================================================================
initial begin
    $dumpfile("tb_tetra_rx_frontend.vcd");
    $dumpvars(0, tb_tetra_rx_frontend);
end

// =============================================================================
// Helper task: apply reset
// =============================================================================
task apply_reset;
    begin
        rst_n_lvds    = 1'b0;
        rst_n_sys     = 1'b0;
        rx_i_lvds     = {IQ_WIDTH{1'b0}};
        rx_q_lvds     = {IQ_WIDTH{1'b0}};
        rx_valid_lvds = 1'b0;
        repeat(20) @(posedge clk_lvds);
        repeat(40) @(posedge clk_sys);
        @(posedge clk_sys); #1;
        rst_n_lvds = 1'b1;
        @(posedge clk_sys); #1;
        rst_n_sys  = 1'b1;
        repeat(10) @(posedge clk_sys);
    end
endtask

// =============================================================================
// Helper task: send one IQ pair (clk_lvds domain)
// =============================================================================
task send_iq_lvds;
    input signed [IQ_WIDTH-1:0] i_val;
    input signed [IQ_WIDTH-1:0] q_val;
    begin
        @(posedge clk_lvds); #2;
        rx_i_lvds     = i_val;
        rx_q_lvds     = q_val;
        rx_valid_lvds = 1'b1;
        @(posedge clk_lvds); #2;
        rx_valid_lvds = 1'b0;
    end
endtask

// =============================================================================
// Helper task: feed a contiguous block of stimulus samples
// =============================================================================
task feed_stimulus;
    input integer start_idx;
    input integer count;
    integer k;
    begin
        for (k = start_idx; k < start_idx + count; k = k + 1) begin
            send_iq_lvds(
                $signed(stim_mem[k][31:16]),
                $signed(stim_mem[k][15:0])
            );
        end
    end
endtask

// =============================================================================
// Helper function: absolute value of signed difference
// =============================================================================
function [IQ_WIDTH:0] abs_diff;
    input signed [IQ_WIDTH-1:0] a;
    input signed [IQ_WIDTH-1:0] b;
    reg signed [IQ_WIDTH:0] diff;
    begin
        diff = $signed({a[IQ_WIDTH-1], a}) - $signed({b[IQ_WIDTH-1], b});
        abs_diff = diff[IQ_WIDTH] ? (~diff + 1'b1) : diff;
    end
endfunction

// =============================================================================
// Output monitor — fires on every out_valid_sys
// Compares phase_valid_count (1-based within phase) against the expected slice
// [exp_start .. exp_start+exp_len-1] for the current phase.
// =============================================================================
always @(posedge clk_sys) begin
    if (out_valid_sys) begin : monitor_block
        reg signed [IQ_WIDTH-1:0] exp_i, exp_q;
        reg [IQ_WIDTH:0] err_i, err_q;
        integer ei;

        valid_count        = valid_count + 1;
        phase_valid_count  = phase_valid_count + 1;

        // Compare if this output falls within the expected window for the phase
        ei = exp_start + (phase_valid_count - 1);
        if (phase_valid_count >= 1 && phase_valid_count <= exp_len) begin
            exp_i = $signed(exp_mem[ei][31:16]);
            exp_q = $signed(exp_mem[ei][15:0]);
            err_i = abs_diff(i_out_sys, exp_i);
            err_q = abs_diff(q_out_sys, exp_q);
            if (err_i > TOLERANCE || err_q > TOLERANCE) begin
                $display("ERROR [exp%0d / phase_out%0d]: I_got=%0d I_exp=%0d (err=%0d)  Q_got=%0d Q_exp=%0d (err=%0d)",
                         ei, phase_valid_count, i_out_sys, exp_i, err_i,
                         q_out_sys, exp_q, err_q);
                error_count = error_count + 1;
            end
        end
    end
end

// =============================================================================
// Main test sequence
// =============================================================================
initial begin
    // -----------------------------------------------------------------------
    // Initialise
    // -----------------------------------------------------------------------
    error_count       = 0;
    valid_count       = 0;
    phase_valid_count = 0;
    exp_start         = 0;
    exp_len           = 0;
    stim_idx          = 0;

    // -----------------------------------------------------------------------
    // Load test vectors
    // -----------------------------------------------------------------------
    $readmemh("tb/vectors/rx_frontend_stimulus.hex", stim_mem);
    $readmemh("tb/vectors/rx_frontend_expected.hex",  exp_mem);
    $display("Loaded stimulus (%0d samples), expected (%0d vectors)", MAX_STIM, MAX_EXP);

    // -----------------------------------------------------------------------
    // Test 0: Assert reset — verify no valid pulses during reset
    // -----------------------------------------------------------------------
    $display("Test 0: Reset assertion");
    apply_reset;
    $display("  PASS — reset released cleanly");

    // -----------------------------------------------------------------------
    // Test 1: DC input — I=0.5, Q=0
    // 2944 stimulus samples → 46 CIC outputs → compare first 8 against expected[0..7]
    // -----------------------------------------------------------------------
    $display("Test 1: DC input (I=0.5 Q=0)");
    phase_valid_count = 0;
    exp_start         = 0;
    exp_len           = DC_EXP_COUNT;

    feed_stimulus(DC_STIM_START, DC_STIM_LEN);

    // Wait for all DC outputs to flush through RRC pipeline
    repeat(200) @(posedge clk_sys);

    begin : t1_check
        integer exp_dc;
        exp_dc = DC_STIM_LEN / CIC_R;
        if (phase_valid_count < exp_dc - 2 || phase_valid_count > exp_dc + 2) begin
            $display("  ERROR [decimation]: DC phase got %0d valid pulses, expected ~%0d",
                     phase_valid_count, exp_dc);
            error_count = error_count + 1;
        end else begin
            $display("  DC phase: %0d valid pulses (expected ~%0d) — OK", phase_valid_count, exp_dc);
        end
    end

    // -----------------------------------------------------------------------
    // Test 2: 1 kHz complex tone — reset DUT first
    // 3456 samples → 54 CIC outputs → compare first 16 against expected[8..23]
    // -----------------------------------------------------------------------
    $display("Test 2: 1 kHz tone");
    apply_reset;
    phase_valid_count = 0;
    exp_start         = DC_EXP_COUNT;          // 8
    exp_len           = TONE_EXP_COUNT;         // 16

    feed_stimulus(TONE_STIM_START, TONE_STIM_LEN);
    repeat(200) @(posedge clk_sys);

    begin : t2_check
        integer exp_tone;
        exp_tone = TONE_STIM_LEN / CIC_R;
        if (phase_valid_count < exp_tone - 2 || phase_valid_count > exp_tone + 2) begin
            $display("  ERROR [decimation]: TONE phase got %0d valid pulses, expected ~%0d",
                     phase_valid_count, exp_tone);
            error_count = error_count + 1;
        end else begin
            $display("  TONE phase: %0d valid pulses (expected ~%0d) — OK", phase_valid_count, exp_tone);
        end
    end

    // -----------------------------------------------------------------------
    // Test 3: π/4-DQPSK — reset DUT first
    // 2688 samples → 42 CIC outputs → compare first 10 against expected[24..33]
    // -----------------------------------------------------------------------
    $display("Test 3: pi/4-DQPSK");
    apply_reset;
    phase_valid_count = 0;
    exp_start         = DC_EXP_COUNT + TONE_EXP_COUNT;  // 24
    exp_len           = DQPSK_EXP_COUNT;                  // 10

    feed_stimulus(DQPSK_STIM_START, DQPSK_STIM_LEN);
    repeat(200) @(posedge clk_sys);

    begin : t3_check
        integer exp_dqpsk;
        exp_dqpsk = DQPSK_STIM_LEN / CIC_R;
        if (phase_valid_count < exp_dqpsk - 2 || phase_valid_count > exp_dqpsk + 2) begin
            $display("  ERROR [decimation]: DQPSK phase got %0d valid pulses, expected ~%0d",
                     phase_valid_count, exp_dqpsk);
            error_count = error_count + 1;
        end else begin
            $display("  DQPSK phase: %0d valid pulses (expected ~%0d) — OK", phase_valid_count, exp_dqpsk);
        end
    end

    // -----------------------------------------------------------------------
    // Final report
    // -----------------------------------------------------------------------
    $display("");
    $display("=== tb_tetra_rx_frontend Summary ===");
    $display("  Total valid pulses received: %0d", valid_count);
    $display("  Errors                     : %0d", error_count);
    if (error_count == 0)
        $display("  RESULT: PASS");
    else
        $display("  RESULT: FAIL");
    $display("=====================================");

    $finish;
end

// =============================================================================
// Timeout watchdog
// =============================================================================
initial begin
    #200_000_000;
    $display("ERROR: Simulation timeout!");
    $finish;
end

endmodule
